### ISSUE TITLE
timecmp 코드 리뷰

### ISSUE THREAD

**Issue by Jack42chj** [kimwoogon/Project2#12]

**Comment by Jack42chj** [comment]
localtime 함수를 연속으로 호출하게 되면 시간이 같아지는 문제를 새로운 변수를 선언해 저장 후 다음 localtime 함수를 불러오는 방법으로 진행을 하였음

**Comment by kimwoogon** [comment]
코드 리뷰 확인했습니다.

**Comment by Dongick** [comment]
코드 리뷰 완료
